#!/usr/bin/env node
// Generates the dictionary-encoded product catalog as docs/catalog.js.
// index.html loads this file via <script src="catalog.js"></script>,
// which exposes _CATALOG_FIELDS, _CATALOG_DICT, and _CATALOG_DATA as globals.
// Usage: node scripts/generate-catalog.js

const fs = require('fs');
const path = require('path');

const CSV_PATH = path.join(__dirname, '..', 'docs', 'product-catalog.csv');
const OUT_PATH = path.join(__dirname, '..', 'docs', 'catalog.js');

// Fields to include in the matrix comparison (16 fields, matching fg.* groups)
const FIELDS = [
  'RatingsCertifications:LuminaireType',
  'Betriebsart',
  'Mounting:MountingMethod',
  'Supply',
  'Monitoring',
  'RatingsCertifications:IngressProtection',
  'RatingsCertifications:IKclass',
  'HousingDimensions:Height',
  'HousingDimensions:Length',
  'HousingDimension:Width',
  'ElectronicPerformanceData:LuminousFluxMains',
  'ElectronicPerformanceData:LuminousFluxEmergency',
  'RatingsCertifications:RecognitionDistance',
  'ElectronicBackupTimes:MaxBackupTime',
  'MaterialData:Material',
  'HousingColorInformation:Color',
];

// RFC-4180 compliant CSV line parser
function parseCsvLine(line) {
  const out = [];
  let cur = '';
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQ) {
      if (c === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; }
        else inQ = false;
      } else cur += c;
    } else {
      if (c === ',') { out.push(cur); cur = ''; }
      else if (c === '"') inQ = true;
      else cur += c;
    }
  }
  out.push(cur);
  return out;
}

function parseCsv(text) {
  const rows = [];
  let cur = '';
  let inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === '"') {
      if (inQ && text[i + 1] === '"') { cur += '""'; i++; }
      else { inQ = !inQ; cur += c; }
    } else if (c === '\n' && !inQ) {
      rows.push(parseCsvLine(cur.replace(/\r$/, '')));
      cur = '';
    } else cur += c;
  }
  if (cur.length) rows.push(parseCsvLine(cur.replace(/\r$/, '')));
  return rows;
}

const text = fs.readFileSync(CSV_PATH, 'utf8');
const rows = parseCsv(text);
const header = rows[0];
const dataRows = rows.slice(1);

const idxOf = name => header.indexOf(name);
const artIdx = idxOf('Artikelnummer');
const abasIdx = idxOf('ABAS-ID');
const pubIdx = idxOf('Veröffentlicht');
const fieldIdxs = FIELDS.map(f => {
  const i = idxOf(f);
  if (i === -1) throw new Error(`Field not found in CSV header: ${f}`);
  return i;
});

const dictSet = new Set();
const records = [];
for (const row of dataRows) {
  if (!row[artIdx]) continue;
  if (row[pubIdx] !== '1') continue;
  const art = row[artIdx];
  const abas = row[abasIdx];
  const vals = fieldIdxs.map(i => {
    const v = (row[i] || '').trim();
    if (v) dictSet.add(v);
    return v;
  });
  records.push([art, abas, vals]);
}

const dict = Array.from(dictSet).sort();
const dictIndex = new Map(dict.map((v, i) => [v, i]));

const encoded = records.map(([art, abas, vals]) => {
  const idxs = vals.map(v => v ? dictIndex.get(v) : '');
  return [art, abas, ...idxs];
});

const rowLines = encoded.map(r => '  ' + JSON.stringify(r)).join(',\n');
const dictStr = JSON.stringify(dict);
const fieldsStr = JSON.stringify(FIELDS);

const out = `// AUTO-GENERATED by scripts/generate-catalog.js — do not edit by hand.
// Source: docs/product-catalog.csv
// Rows: ${encoded.length}, Dict entries: ${dict.length}
// Exposes globals: _CATALOG_FIELDS, _CATALOG_DICT, _CATALOG_DATA

var _CATALOG_FIELDS = ${fieldsStr};

var _CATALOG_DICT = ${dictStr};

var _CATALOG_DATA = [
${rowLines}
];
`;

fs.writeFileSync(OUT_PATH, out);
const sizeKb = (fs.statSync(OUT_PATH).size / 1024).toFixed(1);
console.log(`Wrote ${OUT_PATH} (${sizeKb} KB, rows=${encoded.length}, dict=${dict.length})`);
